# k-Nearest Neighbors, KNN

## Reference

https://ithelp.ithome.com.tw/articles/10220479

sckit-learn: https://scikit-learn.org/stable/modules/generated/sklearn.neighbors.NearestNeighbors.html#sklearn.neighbors.NearestNeighbors

In [37]:
import pandas as pd 
import numpy as np

links = pd.read_csv("ml-latest-small/links.csv")
movies = pd.read_csv("ml-latest-small/movies.csv")
ratings = pd.read_csv("ml-latest-small/ratings.csv")
tags = pd.read_csv("ml-latest-small/tags.csv")

print(links.head(3))
print(movies.head(3))
print(ratings.head(3))
print(tags.head(3))

   movieId  imdbId   tmdbId
0        1  114709    862.0
1        2  113497   8844.0
2        3  113228  15602.0
   movieId                    title  \
0        1         Toy Story (1995)   
1        2           Jumanji (1995)   
2        3  Grumpier Old Men (1995)   

                                        genres  
0  Adventure|Animation|Children|Comedy|Fantasy  
1                   Adventure|Children|Fantasy  
2                               Comedy|Romance  
   userId  movieId  rating  timestamp
0       1        1     4.0  964982703
1       1        3     4.0  964981247
2       1        6     4.0  964982224
   userId  movieId              tag   timestamp
0       2    60756            funny  1445714994
1       2    60756  Highly quotable  1445714996
2       2    60756     will ferrell  1445714992


In [38]:
# merge movie and rating data
data = pd.merge(movies,ratings)
data.head()

movieId             title                                       genres  \
0        1  Toy Story (1995)  Adventure|Animation|Children|Comedy|Fantasy   
1        1  Toy Story (1995)  Adventure|Animation|Children|Comedy|Fantasy   
2        1  Toy Story (1995)  Adventure|Animation|Children|Comedy|Fantasy   
3        1  Toy Story (1995)  Adventure|Animation|Children|Comedy|Fantasy   
4        1  Toy Story (1995)  Adventure|Animation|Children|Comedy|Fantasy   

   userId  rating   timestamp  
0       1     4.0   964982703  
1       5     4.0   847434962  
2       7     4.5  1106635946  
3      15     2.5  1510577970  
4      17     4.5  1305696483

In [39]:
# USER-ITEM Matrix
# pivot_table = User-Item Rating Table (USER-ITEM Matrix)

pivot_table = data.pivot_table(index = ["userId"], columns = ["title"], values = "rating")
pivot_table = pivot_table.fillna(0)
pivot_table.head(10)

title   '71 (2014)  'Hellboy': The Seeds of Creation (2004)  \
userId                                                        
1              0.0                                      0.0   
2              0.0                                      0.0   
3              0.0                                      0.0   
4              0.0                                      0.0   
5              0.0                                      0.0   
6              0.0                                      0.0   
7              0.0                                      0.0   
8              0.0                                      0.0   
9              0.0                                      0.0   
10             0.0                                      0.0   

title   'Round Midnight (1986)  'Salem's Lot (2004)  \
userId                                                
1                          0.0                  0.0   
2                          0.0                  0.0   
3                          0.0                  0.0   
4                          0.0                  0.0   
5                          0.0                  0.0   
6                          0.0                  0.0   
7                          0.0                  0.0   
8                          0.0                  0.0   
9                          0.0                  0.0   
10                         0.0                  0.0   

title   'Til There Was You (1997)  'Tis the Season for Love (2015)  \
userId                                                               
1                             0.0                              0.0   
2                             0.0                              0.0   
3                             0.0                              0.0   
4                             0.0                              0.0   
5                             0.0                              0.0   
6                             0.0                              0.0   
7                             0.0                              0.0   
8                             0.0                              0.0   
9                             0.0                              0.0   
10                            0.0                              0.0   

title   'burbs, The (1989)  'night Mother (1986)  (500) Days of Summer (2009)  \
userId                                                                          
1                      0.0                   0.0                          0.0   
2                      0.0                   0.0                          0.0   
3                      0.0                   0.0                          0.0   
4                      0.0                   0.0                          0.0   
5                      0.0                   0.0                          0.0   
6                      0.0                   0.0                          0.0   
7                      0.0                   0.0                          0.0   
8                      0.0                   0.0                          0.0   
9                      0.0                   0.0                          0.0   
10                     0.0                   0.0                          0.0   

title   *batteries not included (1987)  ...  Zulu (2013)  [REC] (2007)  \
userId                                  ...                              
1                                  0.0  ...          0.0           0.0   
2                                  0.0  ...          0.0           0.0   
3                                  0.0  ...          0.0           0.0   
4                                  0.0  ...          0.0           0.0   
5                                  0.0  ...          0.0           0.0   
6                                  0.0  ...          0.0           0.0   
7                                  0.0  ...          0.0           0.0   
8                                  0.0  ...          0.0           0.0   
9                           

In [40]:
from sklearn.neighbors import NearestNeighbors

knn = NearestNeighbors(metric = 'cosine', algorithm = 'brute')
knn.fit(pivot_table.values)

NearestNeighbors(algorithm='brute', metric='cosine')

In [41]:
user_index = 0
n_neighbors = 6

x = np.array(pivot_table.iloc[user_index, :])
x = x.reshape(1, -1)

nbrs = knn.kneighbors(X = x, n_neighbors = n_neighbors, return_distance=True)

# Array representing the lengths to points, only present if return_distance=True
distances = nbrs[0]
# Topk closet userid: ndices of the nearest points in the population matrix.
indices = nbrs[1] 

In [42]:
distances, indices

(array([[5.55111512e-16, 6.42592290e-01, 6.48438482e-01, 6.54872948e-01,
         6.54965721e-01, 6.65273080e-01]]),
 array([[  0, 265, 312, 367,  56,  90]]))

# Test

In [43]:
pivot_table.iloc[0, :]

title
'71 (2014)                                   0.0
'Hellboy': The Seeds of Creation (2004)      0.0
'Round Midnight (1986)                       0.0
'Salem's Lot (2004)                          0.0
'Til There Was You (1997)                    0.0
                                            ... 
eXistenZ (1999)                              0.0
xXx (2002)                                   0.0
xXx: State of the Union (2005)               0.0
¡Three Amigos! (1986)                        4.0
À nous la liberté (Freedom for Us) (1931)    0.0
Name: 1, Length: 9719, dtype: float64

In [44]:
np.array(pivot_table.iloc[0, :]).reshape(1, -1)

array([[0., 0., 0., ..., 0., 4., 0.]])